### ISSUE TITLE
[Feature] Enable/disable all mods button. Leave comment/like/dislike button for mods.

### ISSUE THREAD

**Issue by GGProGaming** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#16]
**Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.**
No, it is not
**Describe the solution you'd like**
Have a button that enables/disables all mods. Have a button for each mod so people can easily leave a quick comment and rate the mod as people have to go through the process of finding the mod to give suggestions, bug reports, and ratings.
**Describe alternatives you've considered**
Have a manage button for each mod that would take them to the hyperlink of that mod by looking at the mod id.

**Additional context**
None

**Comment by ss-gnalvesteffer** [comment]
+1

I’d like to see this added too! It’s currently a chore to manually disable/enable a bunch of mods, and having a single button to toggle all of them would be great. Also a button to open the workshop page for a mod would be nice too. I try to give feedback on the mods I use, and this would make it more convenient to do so, and I imagine the same for others. This could result in more community engagement as well since it’ll be much easier to get to the a mod’s workshop page.

**Comment by tuxedolabs** [comment]
We have added "Unsubscribe" and "Details..." (workshop page) when right clicking a subscribed mod. It's an interesting idea with disable all. Might look into that later.

**Comment by tuxedolabs** [comment]
"Disable all" is added for each mod category (built-in, subscribed, local) in 0.7.1. I think this should cover the most common use case. Comment like/dislike is not likely to appear in game, since it is already available on workshop.
