### ISSUE TITLE
[Bug] Setting certain keyboard language makes the player unable to move

### ISSUE THREAD

**Issue by Aftersol** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#41]
**Describe the bug**
When the player changes their keyboard language to a certain language with romanization support, the player cannot move if the keyboard is set to type in other characters instead of Roman characters. Instead, it shows what characters to put. Changing the keyboard language back to English reverses the bug

**To Reproduce**
1. Change keyboard language to a certain language (i.e. Chinese and Japanese)
2. Switch to writing non-Roman characters such as pinyin or romaji.
3. Press W, A, S, or D.
4. Switch keyboard language back to English to reverse this bug

**Expected behavior**
A player should move when any of the movement keys (default WASD) are pressed regardless of the keyboard language set.

**Video**
No video about pressing a movement key on the keyboard is shown, but reproducing this bug will get you an idea about this bug.
https://user-images.githubusercontent.com/42478428/118198015-f51b2d80-b404-11eb-9edd-f30517a800fb.mp4

**Environment**
 - Teardown Version 0.7.2 and before
 - OS: Windows 10 Pro 20H2
 - GPU: NVIDIA GTX 960 (runs without graphical issues despite not meeting minimum system requirements)

 - Graphics driver version: 466.27
 - CPU: Intel Core i5 3550P (also runs without graphical issues)

**Additional context**
This bug has been here before keybinding support was implemented in 0.7.2. A potential bug fix is mapping movement to a keypress instead of mapping movement to a character.

EDIT: added wording to clarify a potential bug fix instead of another "bug".

**Comment by tuxedolabs** [comment]
I will let Ludde investigate this, but I suspect it would require a rewrite of the input back-end to make it work since it heavily relies on roman characters at the moment.

**Comment by CoolJWB** [comment]
Appears to be solved since I cannot replicate it anymore.

**Comment by YuLun-bili** [comment]
This bug (or better call it issue) defiantly exists AND it's a very common issue on devices using most logogram languages (Chinese, Japanese, Korean, etc.)

I think the reason you can't replicate it is due to primary language (or default language) of system, which determines the language used to display information and receive inputs. My pc uses Chinese(Simplified, PRC) for both settings and I have to change input method (or language mode*) when using some applications

However, as tuxedo mentioned above, a rewrite would be required to fix this which means this issue may never got fixed. Additionally, few people really regard this to be a bug and this can repeat many times per day on different applications and almost everyone knows what's going on & how to fix it therefore we can accept existence of this issue

*_language mode: for some logogram languages, two language mode is included: logogram language mode and english mode, normally switched using Shift_
