### ISSUE TITLE
[Bug] Quick load unloads sprites and sounds

### ISSUE THREAD

**Issue by carsakiller** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#5]
**Describe the bug**
`LoadSprite()` is used to load sprites for use in your scripts. If you load a sprite, quick save, and then quick load, the sprite appears to be unloaded as it can now not be drawn (`DrawSprite()`). It appears that `init()` is not called when quick loading - not sure if this is intended but it contributes to the sprites not re-loading in the `init()` callback. The same issue affects sounds (`LoadSound()`, `PlaySound()`)

**To Reproduce**
1. Load a sprite in `init()` with `LoadSprite()`
2. Use the menu to make a quick save
3. Quick load the quick save
4. Attempt to draw the sprite
5. Sprite is not drawn as it appears to be unloaded

**Expected behavior**
Sprites are re-loaded when quick loading and are saved when quick saving.

**Environment:**
 - OS: Windows 10 64bit
 - Teardown v0.6.2 (patch 1)

**Additional context**
Perhaps quick save does not save the loaded assets? It may also be that quick save does save them but quick load doesn't load them.

**Comment by CoolJWB** [comment]
Indeed, init is not called at quick load and I'm unable to say if that's intended or not (probably not). However, from what I can see the loaded sprite itself will stay cached and it's only the reference id that is lost. You could try loading the sprite outside the init, and then it should work.

**Comment by kmcgurty** [comment]
Not only does it not call init, I believe it's storing the entire _state_ of the script. Here is a reproducible setup:

```lua
g = {}

g.new = function()
    DebugPrint("Inside new: " .. math.random(100))
end

rand =  math.random(100)

function tick()
    DebugPrint(rand .. type(g.new))
    g.new()
end
```

1. Load this script into a new main.lua, launch the game, and the console will be flooded as expected.

```lua
--The current values are:

rand == 37
type(g) == table
type(g.new) == function
g.new() --prints as expected
```

2. Quick save from the esc menu, then Restart the level (also from the esc menu). Again, everything as expected.

```lua
--The new values are:

rand == 84
type(g) == table
type(g.new) == function
g.new() --prints as expected
```

3. Finally, quick load from the esc menu.

```lua
--All of a sudden, rand == 37 from when we saved and g.new == nil. However, type(g) == table as expected.

rand == 37
type(g) == table
type(g.new) == nil
g.new() --error: main.lua attempt to call a field 'new'
```

If I had to guess what the problem is - I'd say the game saves the LuaState of the script, then when it unloads, the lua engine garbage collects the .new function since it's part of a table. After that, it doesn't get redeclared since it's not actually running the script again.

How to fix it? I'm not sure of the best way. Probably would be to restart the script entirely like it does when you restart the level.

**Comment by Thomasims** [comment]
This is explained partly in the blogpost about quicksaving; The game tries to restore the state of the script to what it was when doing the quicksave but it only keeps serializable functions from _G and known references like loaded assets. The process goes more or less like this:
```
Normal start:
- Load script in a new context and run it. (Everything not in a function is ran)
- Call init() from that new context
- tick/update/draw loop

Quickload:
- Load script in a new context and run it. (Everything not in a function is ran)
- Deserialize tables in quicksave (recursive), override values in _G with them (non-recursive!)
- Send command 'quickload'
- tick/update/draw loop
```

This shouldn't cause an issue with sprites and sounds if they're stored as global variables as they simply get set back to the saved handle during the quickloading step. That isn't to say the system is flawless however, as noted in the blog post and in your experiment there are a few cases not covered by the algorithm that either cause crashes or inconsistencies in the Lua state that you must work around:
```
- Recursive/Cyclic structures in _G cause the serializer to crash.
- Unserializable values in tables (functions, metatables, etc..) get replaced by nil on quickloading.
- Everything that is not directly in _G is not saved.
- Complex mechanisms such as coroutines are not saved.
```
We can't expect the devs to fix all of these issues, 3 and 4 are very difficult to approach and would most likely require a full state serializer. 1 and 2 are seemingly easy to fix but it's probably not very high on their TODO list since "it works if you do it the way they intended".

**Comment by kmcgurty** [comment]
@Thomasims That's very interesting, thanks for the insight. I'm wondering if it makes more sense to store the state of mods that are [tagged](https://teardowngame.com/modding/#info.txt) `Map, Gameplay, Asset, Vehicle` and not `Tool` (assuming mods tagged `Tool` are generally `.lua` script mods?). Since it makes sense to store actual assets, I can't think of a reason to store mods that are only `.lua` scripts.

Perhaps even better would be to have a config option in `info.txt` that excludes the mod from being saved. It would at least solve the issue I'm running into, anyway.

**Comment by tuxedolabs** [comment]
Thomasims description is accurate. I don't think the original bug report here is an issue, but rather an issue with how the script was implemented. Sprites and other assets are saved and restored during quicksave/quickload. If handle is stored in a regular global variable it should work as expected.
