### ISSUE TITLE
[Bug] Shadows cease to exist higher up.

### ISSUE THREAD

**Issue by nonameplz** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#56]
### Describe the bug

https://user-images.githubusercontent.com/47130559/130371300-2bbabe30-4b9a-4118-9863-b0534e935e8d.mp4

### Steps to reproduce the behavior

1. Go to any map
2. Grab an object
3. Bring it high in the air

### Expected behavior

Object would continue to create shadows when bringing it high up

### Environment

- Teardown Version 0.74
- OS: Windows 10
- GPU: NVIDIA GeForce RTX 3070 Ti
- Graphics driver version: 30.0.14.7141
- CPU: 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz   3.50 GHz

**Comment by RoverBot-Dev** [comment]
Objects' shadows are only rendered inside the shadow volume to make performance better.
This is why this bug happens

**Comment by Thomasims** [comment]
This is a known limitation of the engine, what you're seeing in the video is simply the prop going above the top of the shadow volume.
This limitation is generally accepted since nothing is meant to leave the shadow volume in normal gameplay.
If you wish to learn more about how this works you can see [this blog post](https://blog.tuxedolabs.com/2018/10/17/from-screen-space-to-voxel-space.html) which has a lot of information about how teardown rendering works.
