### ISSUE TITLE
[Bug] File substitution does not work for core Lua files in campaign mode

### ISSUE THREAD

**Issue by DimasVoxel** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#68]
### Describe the bug

File substitution does not work for core Lua files in capaign mode.

Replacing pipe bombs with bananas works. 
Replacing core lua files does not have any effect and doesn't seem to affect campaign mode.

### Steps to reproduce the behavior

Create a mod that replaces a lua file for example:
ModFolder/data/script/robots.lua

Example mod that makes bots say ouch if shot.
Video example:
https://imgur.com/a/LIMgNJx

[Ouch_Bots.zip](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/files/7661706/Ouch_Bots.zip)

### Expected behavior

The mod should be able to substitute the files that are located in /data/script/ and change the behavior in campaign mode.
This only seems to work on mod maps right now.

### Environment

- Teardown Version: 0.9.0
- OS: Windows 10
- GPU: 2060 6GB
- CPU: Ryzen 7 3700x

**Comment by tuxedolabs** [comment]
I'm investigating this issue. It seems to be related to binary loading of maps, and I have not yet decided if I should try to fix it or not. Overriding the default scripts is something we probably should steer away from anyways, since it can quickly lead to unexpected and hard to debug scenarios when scripts go out of sync with updates.
