### ISSUE TITLE
[Bug] Big destructions cause cpu and gpu usage to go down

### ISSUE THREAD

**Issue by DaMysticRaffy** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#70]
### Describe the bug

GPU and CPU usage go down when big destructions occur

### Steps to reproduce the behavior

1. Go to any map
2. Destroy something big
3. See error

### Expected behavior

For CPU and GPU usage to go up

https://user-images.githubusercontent.com/67703577/146119511-27ce383e-bdd6-44ab-a406-c0fa2a39316f.mp4

.

### Environment

- Teardown Version 0.9.0
- OS: Windows 11
- GPU: RTX 3070
- Graphics driver version: 497.09
- CPU: Intel Core i5-12600k

### Additional context

Note: [Originally reported on my old computer in August](https://github.com/Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker/issues/57). Built new pc in November and wanted to see if I could replicate it and still could.

**Comment by Thomasims** [comment]
CPU usage does go up in the video, Looking at your CPU I see you have 10 cores which would make sense considering the usage peeked at ~50% (The game can't make perfect use of all those cores at once, [although it tries!](http://twitter.com/tuxedolabs/status/1357687672215658504))
GPU usage going down makes sense since the game is freezing trying to compute physics, it essentially has nothing to do while it waits for the game.

**Comment by tuxedolabs** [comment]
This is expected behavior
