### ISSUE TITLE
[Bug] SetToolTransform not working correctly with tools from other mods

### ISSUE THREAD

**Issue by byblo** [Teardown-Issue-Tracker-Maintainers/Teardown-Issue-Tracker#72]
### Describe the bug

Applying that function to tools from mods differs from game's internal tools.

### Steps to reproduce the behavior

Toggle this code to any tool (for instance, the "M1 Garand", or the "Mini Flame Thrower" from the workshop), and see the differences:

local offset = Transform(Vec(0.0, 0, 0))
SetToolTransform(offset)

Now, the garand is way too below, or the mini flame thrower is way too high (vox original position)

### Expected behavior

- On a offical tool, there is no visible position change, which is expected since the offset has no change (0, 0, 0).

- On a mod's tool, the item now looks like its own SetToolTransform calls are not applied anymore for some reason (if the mod called SetToolTransform(0,-1,0) , it doesnt apply anymore or seems to be overwritten by the lastest call)

### Environment

steam version

### Additional context

My goal is to change only the second parameter only (the swaying) for the currently selected tool, official or mod, since the crazy swaying is giving me dizzyness.

**Comment by Thomasims** [comment]
This looks like expected behavior for the function itself as setting multiple transforms each tick wouldn't make much sense.
Maybe the sway should be split apart into its own control or handled as an accessibility setting like you've requested in your other issue (#73) but this function should never be used blindly on a tool from a different mod.
